// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwQbiYAQh-vmisA__0piUbxmbqRiFH1GE',
    appId: '1:273862709486:web:be2f04c855d4e6442e23ff',
    messagingSenderId: '273862709486',
    projectId: 'chat-app-ca8f8',
    authDomain: 'chat-app-ca8f8.firebaseapp.com',
    storageBucket: 'chat-app-ca8f8.appspot.com',
    measurementId: 'G-Q7D0JZB0VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDps88R_CjTqxfUDb004lfcvNqel7ZOe50',
    appId: '1:273862709486:android:d071bd040e79ca592e23ff',
    messagingSenderId: '273862709486',
    projectId: 'chat-app-ca8f8',
    storageBucket: 'chat-app-ca8f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2U3uNgi9chxu50F7kwUN6nXdzvPWp3yU',
    appId: '1:273862709486:ios:b6d843529b22d6052e23ff',
    messagingSenderId: '273862709486',
    projectId: 'chat-app-ca8f8',
    storageBucket: 'chat-app-ca8f8.appspot.com',
    iosClientId: '273862709486-9qtt98sfa0r5nqagglg5qv24327ckf1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2U3uNgi9chxu50F7kwUN6nXdzvPWp3yU',
    appId: '1:273862709486:ios:b6d843529b22d6052e23ff',
    messagingSenderId: '273862709486',
    projectId: 'chat-app-ca8f8',
    storageBucket: 'chat-app-ca8f8.appspot.com',
    iosClientId: '273862709486-9qtt98sfa0r5nqagglg5qv24327ckf1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
